### ISSUE TITLE
it's unclear how this POM is supposed to be used

### ISSUE THREAD

**Issue by yegor256** [egis/parent#7]
It's unclear, how this parent POM is supposed to be used. Would be great to explain the entire use case in `README.md`. For example:

 1. You create a new project with the following `pom.xml`, as an example: ...
 2. You specify environment variables X, Y, Z
 3. You configure `settings.xml` this way: ...
 4. You run it like `mvn clean install`
 5. You get A, B, and C

@Egis-Moshe If you can't write it down like this I can help, but I need an example project. Show me some repository, which will need this parent and I'll try to figure out.

**Comment by Egis-Moshe** [comment]
@yegor256  Please check now

**Comment by yegor256** [comment]
@Egis-Moshe would be great if you submit changes to any files in the repo through pull requests. that will help us to review changes, discuss them and approve. at the moment it's not very critical, but when we start working with the code I will ask you to revoke write permissions from **everybody**, including myself and yourself. only rultor will have write permissions to all repos.

**Comment by yegor256** [comment]
@Egis-Moshe what I see now in README contradicts to what Maven recommends to do. I'm trying to understand is there a reason for that or it's just a mistake. to help me understand better I really need to see a project that is using (or will use) this parent POM. can you share a link?

**Comment by Egis-Moshe** [comment]
What do you suggest instead?
These are our core standalone libraries github.com/egis/Utils github.com/egis/Kernel github.com/egis/PQL
To be joined by ConversionEngine and StorageService from github.com/egis/PT and
then eventually PT as well.
We also have client repositories that include a mix of Java, Javascript,
resources etc.. e.g. github.com/egis/MRP github.com/egis/Travel





On Tue, Jun 28, 2016 7:02 PM, Yegor Bugayenko notifications@github.com wrote:
@Egis-Moshe what I see now in README contradicts to what Maven recommends to do. I'm trying
to understand is there a reason for that or it's just a mistake. to help me
understand better I really need to see a project that is using (or will use)
this parent POM. can you share a link?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub , or mute the thread .



Moshe

**Comment by Egis-Moshe** [comment]
@yegor256 re permissions going forward 100%

**Comment by yegor256** [comment]
@Egis-Moshe looks like you're a mix of tools (Gradle, Maven, Ant). I would suggest to migrate to Maven and stay with it. Let me try to modify this README and we'll discuss

**Comment by yegor256** [comment]
@Egis-Moshe PR #8 is attached (I've spent 3 hours up to date)

**Comment by yegor256** [comment]
@Egis-Moshe closing
